"""Generate data.js for the typing game from the Ascent career-planner glossary.

Run with the Ascent venv python (it needs PyYAML):

    "<Ascent>/.venv/Scripts/python.exe" build_data.py

Source of truth stays in the Ascent project; this only exports a snapshot.
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

ASCENT = Path(os.environ.get("ASCENT_DIR", r"C:\Users\aaron\projects\Finance agent\career-planner"))
OUT = Path(__file__).parent / "data.js"

# Unicode -> plain ASCII so every target string is something a US keyboard can
# actually produce. Anything not mapped and not ASCII printable is dropped.
SYMBOLS = {
    # dashes / ellipsis
    "\u2014": "-", "\u2013": "-", "\u2010": "-", "\u2011": "-", "\u2212": "-",
    "\u2026": "...",
    "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
    # operators
    "\u00b7": "*", "\u00d7": "*", "\u22c5": "*", "\u2022": "*",
    "\u221a": "sqrt ",
    "\u2264": "<=", "\u2265": ">=",
    "\u00b0": " deg",
    # superscripts / subscripts
    "\u00b2": "^2", "\u00b3": "^3", "\u2070": "^0", "\u2074": "^4",
    "\u2080": "0", "\u2081": "1", "\u2082": "2", "\u2083": "3", "\u2084": "4",
    "\u00bd": "1/2", "\u00bc": "1/4", "\u00be": "3/4",
    # greek + summation
    "\u0394": "Delta ", "\u03a3": "Sum ",
    "\u03b1": "alpha ", "\u03b2": "beta ", "\u03b3": "gamma ", "\u03b4": "delta ",
    "\u03b5": "epsilon ", "\u03b6": "zeta ", "\u03b7": "eta ", "\u03b8": "theta ",
    "\u03b9": "iota ", "\u03ba": "kappa ", "\u03bb": "lambda ", "\u03bc": "mu ",
    "\u03bd": "nu ", "\u03be": "xi ", "\u03c0": "pi ", "\u03c1": "rho ",
    "\u03c3": "sigma ", "\u03c2": "sigma ", "\u03c4": "tau ", "\u03c5": "upsilon ",
    "\u03c6": "phi ", "\u03c7": "chi ", "\u03c8": "psi ", "\u03c9": "omega ",
    "\u0393": "Gamma ", "\u0398": "Theta ", "\u039b": "Lambda ", "\u03a9": "Ohm ",
}


def sanitize(s: str) -> str:
    out: list[str] = []
    for ch in s:
        if ch.isspace():
            out.append(" ")
        elif ch in SYMBOLS:
            out.append(SYMBOLS[ch])
        elif ord(ch) < 128 and ch.isprintable():
            out.append(ch)
        # anything else is dropped
    return re.sub(r" {2,}", " ", "".join(out)).strip()


DECK = {
    "controls": "controls",
    "ml": "ml",
    "electrical": "mech",
    "mechanical": "mech",
    "mechanisms": "mech",
}


def main() -> int:
    sys.path.insert(0, str(ASCENT))
    import glossary  # noqa: E402  (needs Ascent on sys.path)

    rows: list[dict] = []
    term_changed: list[str] = []
    for entry in glossary.as_list():
        raw_term = str(entry.get("term") or "")
        raw_def = str(entry.get("def") or "")
        term, defn = sanitize(raw_term), sanitize(raw_def)
        if not term or not defn:
            continue
        if term != raw_term:
            term_changed.append(f"{raw_term!r} -> {term!r}")
        rows.append(
            {
                "t": term,            # what the player types (term)
                "d": defn,            # what the player types (definition)
                "T": raw_term,        # original, for display
                "D": raw_def,         # original, for reference
                "f": str(entry.get("formula") or ""),
                "deck": DECK.get(str(entry.get("domain")), "ml"),
                "dom": str(entry.get("domain") or "general"),
            }
        )

    rows.sort(key=lambda r: r["t"].lower())

    decks: dict[str, int] = {"all": len(rows)}
    for r in rows:
        decks[r["deck"]] = decks.get(r["deck"], 0) + 1

    js = (
        "// Generated by build_data.py -- do not edit by hand.\n"
        "// Source: Ascent career-planner vocab_definitions.yaml + engineering_formulas.yaml\n"
        "window.VOCAB = "
        + json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    OUT.write_text(js, encoding="utf-8")

    print(f"wrote {OUT.name}: {len(rows)} entries, {len(js)} bytes")
    print("decks:", decks)
    if term_changed:
        print("terms normalized:")
        for line in term_changed:
            print("  ", line)
    else:
        print("terms normalized: none (all already ASCII)")
    print("longest definition:", max(len(r["d"]) for r in rows), "chars")
    print("shortest definition:", min(len(r["d"]) for r in rows), "chars")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
