/* =====================================================================
   VOCAB STRIKE — a ZType-style typing game over a bundled glossary.

   Two phases:
     DEFEND  enemy ships drift in from the right carrying a TERM.
             Type the term exactly to destroy the ship.
             A wrong key locks the word until you press Backspace.
     DECODE  once the wave is clear, type each salvaged DEFINITION
             before its timer runs out.

   Data comes from data.js (generated by build_data.py from the Ascent
   career-planner YAML glossaries). Everything is plain ASCII already, so
   what is drawn is exactly what must be typed.
   ===================================================================== */
(() => {
'use strict';

/* ------------------------------------------------------------------ *
 * palette — mirrors Ascent frontend/src/style.css
 * ------------------------------------------------------------------ */
const C = {
  bg:'#050509', ink900:'#0b0b15', ink850:'#10101d', ink800:'#161626',
  ink700:'#1f1f31', ink600:'#2b2b42',
  fg:'#eaecf5', muted:'#9aa0ba', faint:'#5f6589',
  line:'#20202f', lineStrong:'#313148',
  accent:'#6366f1', accent2:'#8b5cf6', accent3:'#818cf8',
  cyan:'#22d3ee', pos:'#10b981', warn:'#f59e0b', danger:'#f43f5e',
};
const SANS = '"Inter", system-ui, -apple-system, "Segoe UI", sans-serif';
const MONO = '"JetBrains Mono", ui-monospace, "Cascadia Mono", Consolas, monospace';

const HUD_H = 56, PROMPT_H = 126;
const PX = 78;                       // player ship x

const DECKS = [
  { id:'all',      label:'All systems' },
  { id:'controls', label:'Controls'    },
  { id:'ml',       label:'ML / CV'     },
  { id:'mech',     label:'EE + Mech'   },
  { id:'mine',     label:'My words'    },
];
const DIFFS = [
  { id:'easy',   label:'Cadet',    spd:0.70, spawn:1.30, timer:1.45, hp:5 },
  { id:'normal', label:'Operator', spd:1.00, spawn:1.00, timer:1.00, hp:3 },
  { id:'hard',   label:'Vanguard', spd:1.45, spawn:0.76, timer:0.76, hp:2 },
];
const DECK_NOTE = {
  all:'every term', controls:'PLC, ladder, Modbus',
  ml:'models, training, vision', mech:'circuits, motion, mechanisms',
  mine:'added by you',
};

/* ------------------------------------------------------------------ *
 * dom
 * ------------------------------------------------------------------ */
const cv  = document.getElementById('game');
const ctx = cv.getContext('2d');
const $   = (id) => document.getElementById(id);
const menuEl = $('menu'), overEl = $('over'), pauseEl = $('pause'), ctlEl = $('ctl');

/* ------------------------------------------------------------------ *
 * state
 * ------------------------------------------------------------------ */
const S = {
  mode:'menu', scene:null,            // scene = gameplay view being drawn
  deck:'all', diff:DIFFS[1],
  wave:1, score:0, hp:3, maxHp:3,
  combo:0, bestCombo:0,
  adv:0, err:0, killed:0, decoded:0, missed:0, salvageCount:0,
  playMs:0,
  enemies:[], particles:[], beams:[], floats:[], stars:[],
  focus:null, pool:[], salvage:[], spawnLeft:0, spawnT:0, waveSize:3,
  queue:[], qi:0, decodedBefore:0, card:null, cardProg:0, cardT:0, cardLimit:0, cardState:'', cardHold:0,
  flash:0, flashCol:C.danger, shake:0,
  toast:null, muted:false, startAt:0,
  errKey:null,                  // committed mistake — Backspace clears it
};

let W = 0, H = 0, DPR = 1;

/* ------------------------------------------------------------------ *
 * utils
 * ------------------------------------------------------------------ */
const rnd  = (a, b) => a + Math.random() * (b - a);
const pick = (a) => a[(Math.random() * a.length) | 0];
const clamp = (v, a, b) => v < a ? a : v > b ? b : v;
function shuffle(a) {
  a = a.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = (Math.random() * (i + 1)) | 0;
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
function rr(x, y, w, h, r) {
  r = Math.min(r, w / 2, h / 2);
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}
const eq = (a, b) => a.toLowerCase() === b.toLowerCase();
function measure(txt, font) { ctx.font = font; return ctx.measureText(txt).width; }

const mult = () => Math.min(5, 1 + Math.floor(S.combo / 15));
const acc  = () => (S.adv + S.err) ? (S.adv / (S.adv + S.err)) * 100 : 100;
const wpm  = () => S.playMs > 1000 ? (S.adv / 5) / (S.playMs / 60000) : 0;

function keyLabel(ch) {
  if (ch === ' ') return 'SPACE';
  if (ch >= 'A' && ch <= 'Z') return ch.toLowerCase();   // matching is case-insensitive
  if ('!@#$%^&*()_+{}|:"<>?~`'.includes(ch)) return 'shift+' + ch;
  return ch;
}

/* ------------------------------------------------------------------ *
 * audio — tiny synth, no assets
 * ------------------------------------------------------------------ */
let AC = null;
function ac() {
  if (!AC) { try { AC = new (window.AudioContext || window.webkitAudioContext)(); } catch (e) { return null; } }
  if (AC.state === 'suspended') AC.resume();
  return AC;
}
function tone(f, dur, type, gain, f2) {
  const a = ac(); if (!a || S.muted) return;
  const o = a.createOscillator(), g = a.createGain();
  o.type = type || 'square';
  o.frequency.setValueAtTime(f, a.currentTime);
  if (f2) o.frequency.exponentialRampToValueAtTime(Math.max(30, f2), a.currentTime + dur);
  g.gain.setValueAtTime(0.0001, a.currentTime);
  g.gain.exponentialRampToValueAtTime(gain || 0.05, a.currentTime + 0.008);
  g.gain.exponentialRampToValueAtTime(0.0001, a.currentTime + dur);
  o.connect(g).connect(a.destination);
  o.start(); o.stop(a.currentTime + dur + 0.02);
}
function noise(dur, gain, freq) {
  const a = ac(); if (!a || S.muted) return;
  const n = Math.floor(a.sampleRate * dur);
  const buf = a.createBuffer(1, n, a.sampleRate);
  const d = buf.getChannelData(0);
  for (let i = 0; i < n; i++) d[i] = (Math.random() * 2 - 1) * (1 - i / n);
  const src = a.createBufferSource(); src.buffer = buf;
  const f = a.createBiquadFilter(); f.type = 'lowpass'; f.frequency.value = freq || 1400;
  const g = a.createGain(); g.gain.value = gain || 0.16;
  src.connect(f).connect(g).connect(a.destination);
  src.start();
}
const sfx = {
  key()     { tone(880, 0.03, 'square', 0.028); },
  err()     { tone(150, 0.13, 'sawtooth', 0.05, 90); },
  kill()    { noise(0.34, 0.2, 1800); tone(340, 0.16, 'triangle', 0.07, 110); },
  lock()    { tone(520, 0.07, 'square', 0.05); setTimeout(() => tone(780, 0.1, 'square', 0.05), 70); },
  good()    { [660, 880, 1180].forEach((f, i) => setTimeout(() => tone(f, 0.13, 'triangle', 0.055), i * 65)); },
  bad()     { tone(300, 0.22, 'sawtooth', 0.05, 120); },
  hurt()    { noise(0.4, 0.24, 700); tone(90, 0.3, 'sawtooth', 0.07, 45); },
  wave()    { [440, 587, 740].forEach((f, i) => setTimeout(() => tone(f, 0.16, 'triangle', 0.05), i * 90)); },
  over()    { [440, 330, 247, 165].forEach((f, i) => setTimeout(() => tone(f, 0.34, 'sawtooth', 0.06), i * 150)); },
};

/* ------------------------------------------------------------------ *
 * data
 * ------------------------------------------------------------------ */
const BASE_VOCAB = (window.VOCAB || []).filter((e) => e.t && e.d);
let VOCAB = BASE_VOCAB.concat(customWords());

/* Words the player added in the menu (words.js) — no-op if that script
   is missing, so the game still boots from data.js alone. */
function customWords() {
  return window.VS_WORDS ? window.VS_WORDS.entries() : [];
}
function reloadVocab() { VOCAB = BASE_VOCAB.concat(customWords()); }

function inDeck(e, id) {
  if (id === 'all') return true;
  if (id === 'mine') return !!e.mine;
  return e.deck === id;
}
function rebuildPool() {
  const src = VOCAB.filter((e) => inDeck(e, S.deck));
  S.pool = shuffle(src.length ? src : VOCAB);
}
function nextCard() {
  if (!S.pool.length) rebuildPool();
  return S.pool.pop() || pick(VOCAB);
}

/* ------------------------------------------------------------------ *
 * sizing
 * ------------------------------------------------------------------ */
function resize() {
  DPR = Math.min(2, window.devicePixelRatio || 1);
  W = window.innerWidth; H = window.innerHeight;
  cv.width = Math.round(W * DPR); cv.height = Math.round(H * DPR);
  ctx.setTransform(DPR, 0, 0, DPR, 0, 0);
}
window.addEventListener('resize', resize);

function initStars() {
  S.stars = [];
  for (let i = 0; i < 170; i++) {
    S.stars.push({ x: Math.random() * W, y: Math.random() * H, z: rnd(0.25, 1) });
  }
}

/* ------------------------------------------------------------------ *
 * flow
 * ------------------------------------------------------------------ */
function show(el, on) { el.hidden = !on; }

function startGame() {
  S.diff = DIFFS.find((d) => d.id === S.diff.id) || DIFFS[1];
  S.wave = 1; S.score = 0; S.combo = 0; S.bestCombo = 0;
  S.adv = 0; S.err = 0; S.killed = 0; S.decoded = 0; S.missed = 0; S.salvageCount = 0;
  S.playMs = 0; S.maxHp = S.diff.hp; S.hp = S.diff.hp;
  S.enemies = []; S.particles = []; S.beams = []; S.floats = [];
  S.focus = null; S.queue = []; S.card = null; S.toast = null; S.errKey = null;
  S.flash = 0; S.shake = 0;
  rebuildPool();
  show(menuEl, false); show(overEl, false); show(pauseEl, false); show(ctlEl, true);
  S.mode = 'defend'; S.scene = 'defend';
  startWave();
  ac();
}

function startWave() {
  S.enemies = []; S.focus = null; S.salvage = [];
  S.errKey = null;                                   // fresh wave, fresh slate
  S.waveSize = Math.min(3 + Math.floor((S.wave - 1) / 2), 5);
  S.spawnLeft = S.waveSize; S.spawnT = 0.55;
}

function spawn() {
  const e = nextCard();
  const txt = e.t;
  const maxW = Math.min(330, W * 0.30);
  let fs = 15;
  let tw = measure(txt, `600 ${fs}px ${MONO}`);
  if (tw > maxW) { fs = Math.max(11, fs * maxW / tw); tw = measure(txt, `600 ${fs}px ${MONO}`); }
  const top = HUD_H + 34, bot = Math.max(top + 10, H - PROMPT_H - 34);
  // best of a few random rows, so a new ship doesn't sit on top of another
  let y = top, gap = -1;
  for (let i = 0; i < 8; i++) {
    const cy = rnd(top, bot);
    const d = Math.min(Infinity, ...S.enemies.map((o) => Math.abs(o.y - cy)));
    if (d > gap) { gap = d; y = cy; }
  }
  S.enemies.push({
    e, txt, fs, tw,
    w: tw + 46, h: 44,
    x: W + Math.max(90, tw / 2 + 30), y,
    vx: 46 * S.diff.spd * (1 + (S.wave - 1) * 0.075),
    prog: 0, born: performance.now(), wob: Math.random() * 6.28,
  });
}

function pushFloat(x, y, text, col) {
  S.floats.push({ x, y, text, col, t: 0, dur: 1.05 });
}
function burst(x, y, col, n) {
  for (let i = 0; i < n; i++) {
    const a = Math.random() * 6.283, sp = rnd(50, 330);
    S.particles.push({
      x, y, vx: Math.cos(a) * sp, vy: Math.sin(a) * sp,
      t: 0, dur: rnd(0.35, 0.8), size: rnd(1.4, 3.6), col,
    });
  }
}
function setToast(text, sub, dur, col) {
  S.toast = { text, sub: sub || '', t: 0, dur: dur || 2, col: col || C.accent3 };
}

/* ---- defend ---- */
function handleDefendChar(ch) {
  const f = S.focus;
  if (f && f.prog < f.txt.length) {
    if (eq(ch, f.txt[f.prog])) { advanceEnemy(f); return; }
    if (f.prog > 0) { mistake(ch); return; }          // locked in mid-word
  }
  // pick the nearest ship whose first character matches
  let best = null;
  for (const e of S.enemies) {
    if (e.prog === 0 && eq(ch, e.txt[0])) { if (!best || e.x < best.x) best = e; }
  }
  if (best) { S.focus = best; advanceEnemy(best); return; }
  mistake(ch);
}

function advanceEnemy(e) {
  e.prog++;
  S.adv++; S.combo++;
  S.bestCombo = Math.max(S.bestCombo, S.combo);
  S.score += 1 * mult();
  sfx.key();
  if (e.prog >= e.txt.length) killEnemy(e);
}

function killEnemy(e) {
  const i = S.enemies.indexOf(e);
  if (i < 0) return;
  S.enemies.splice(i, 1);
  if (S.focus === e) S.focus = null;
  S.killed++;
  S.salvageCount++;
  S.salvage.push(e.e);
  const gain = Math.round(60 * mult() + (W - e.x) * 0.05);
  S.score += gain;
  S.beams.push({ x1: PX, y1: midY(), x2: e.x, y2: e.y, t: 0, dur: 0.16 });
  burst(e.x, e.y, C.cyan, 26);
  burst(e.x, e.y, C.accent, 14);
  pushFloat(e.x, e.y - 30, '+' + gain, C.pos);
  S.flash = 0.10; S.flashCol = C.cyan;
  sfx.kill();
  if (e.prog >= e.txt.length && e.txt.length > 12) sfx.lock();
}

function mistake(ch) {
  S.errKey = ch == null ? '?' : ch;   // committed mistake — Backspace clears it
  S.err++;
  S.combo = 0;
  S.shake = Math.min(11, S.shake + 5);
  S.flash = 0.12; S.flashCol = C.danger;
  sfx.err();
}

/* clear a committed mistake — the word accepts keys again after this */
function clearMistake() {
  if (!S.errKey) return;
  S.errKey = null;
  sfx.key();
}

function hurt() {
  S.hp--; S.combo = 0;
  S.shake = 16;
  S.flash = 0.30; S.flashCol = C.danger;
  S.beams.push({ x1: 0, y1: midY(), x2: PX, y2: midY(), t: 0, dur: 0.2, red: true });
  sfx.hurt();
  if (S.hp <= 0) gameOver();
}

const midY = () => (HUD_H + 10 + (H - PROMPT_H - 10)) / 2;

function updateDefend(dt) {
  S.spawnT -= dt;
  if (S.spawnLeft > 0 && S.spawnT <= 0) {
    spawn(); S.spawnLeft--;
    S.spawnT = Math.max(0.7, (2.0 - S.wave * 0.07)) * S.diff.spawn;
  }
  for (let i = S.enemies.length - 1; i >= 0; i--) {
    const e = S.enemies[i];
    e.x -= e.vx * dt;
    e.wob += dt * 2;
    if (e.x - e.w / 2 <= PX + 22) {
      S.enemies.splice(i, 1);
      if (S.focus === e) S.focus = null;
      S.salvageCount++; S.salvage.push(e.e);               // captured on impact, not a kill
      burst(e.x, e.y, C.danger, 22);
      pushFloat(PX, midY() - 34, '-1 HULL', C.danger);
      hurt();
      if (S.mode !== 'defend') return;
    }
  }
  if (S.focus && !S.enemies.includes(S.focus)) S.focus = null;
  if (S.spawnLeft === 0 && S.enemies.length === 0 && S.mode === 'defend') beginDecode();
}

function beginDecode() {
  S.mode = 'decode'; S.scene = 'decode';
  S.queue = shuffle(S.salvage);
  S.qi = 0; S.decodedBefore = S.decoded;
  setToast('WAVE ' + S.wave + ' CLEARED', S.queue.length + ' signals salvaged — type the definitions', 2.1, C.pos);
  sfx.wave();
  loadCard();
}

function loadCard() {
  S.card = S.queue[S.qi];
  S.cardProg = 0;
  S.cardState = 'typing';
  S.errKey = null;                                   // each card starts clean
  S.cardLimit = (6 + 0.25 * S.card.d.length) * S.diff.timer;
  S.cardT = S.cardLimit;
}

function advanceCard() {
  S.cardProg++;
  S.adv++;
  S.combo++;
  S.bestCombo = Math.max(S.bestCombo, S.combo);
  S.score += 2 * mult();
  sfx.key();
  if (S.cardProg >= S.card.d.length) {
    const bonus = Math.round((S.cardT / S.cardLimit) * 140);
    const gain = Math.round(150 * mult()) + bonus;
    S.score += gain;
    S.decoded++;
    S.cardState = 'done'; S.cardHold = 1.7;
    // float above the panel so it never lands on the result banner
    const b = decodeBox();
    pushFloat(W / 2, b.py - 34, '+' + gain + (bonus ? '  speed +' + bonus : ''), C.pos);
    S.flash = 0.14; S.flashCol = C.pos;
    sfx.good();
  }
}

function failCard() {
  S.missed++; S.combo = 0;
  S.cardState = 'miss'; S.cardHold = 2.1;
  S.flash = 0.20; S.flashCol = C.warn;
  sfx.bad();
}

function skipCard() {
  if (S.cardState !== 'typing') return;
  S.missed++; S.combo = 0;
  S.cardState = 'skip'; S.cardHold = 0.9;
  sfx.bad();
}

function updateDecode(dt) {
  if (S.cardState === 'typing') {
    S.cardT -= dt;
    if (S.cardT <= 0) { S.cardT = 0; failCard(); }
  } else if (S.cardState === 'done' || S.cardState === 'miss' || S.cardState === 'skip') {
    S.cardHold -= dt;
    if (S.cardHold <= 0) nextCardInQueue();
  }
}
function nextCardInQueue() {
  S.qi++;
  if (S.qi >= S.queue.length) endDecode();
  else loadCard();
}

function endDecode() {
  const ok = S.decoded - S.decodedBefore, n = S.queue.length;
  S.wave++;
  S.mode = 'defend'; S.scene = 'defend';
  startWave();
  setToast('WAVE ' + S.wave, 'hull ' + S.hp + '/' + S.maxHp + ' — ' + ok + '/' + n + ' definitions banked', 1.9, C.accent3);
}

function gameOver() {
  S.mode = 'over'; S.scene = null;
  show(ctlEl, false); show(pauseEl, false);
  const a = Math.round(acc()), p = Math.round(wpm());
  $('oS').textContent = S.score.toLocaleString();
  $('oW').textContent = S.wave;
  $('oP').textContent = p;
  $('oA').textContent = a + '%';
  $('oK').textContent = S.killed;
  $('oD').textContent = S.decoded;
  $('oC').textContent = S.bestCombo;
  $('oM').textContent = S.missed;
  $('verdict').textContent = S.wave >= 8 ? 'Glossary Master' : S.wave >= 5 ? 'Deep Run' : S.wave >= 3 ? 'Holding The Line' : 'Hull Breach';
  const vc = S.wave >= 5 ? '16,185,129' : S.wave >= 3 ? '245,158,11' : '244,63,94';
  $('verdict').style.cssText = `background:rgba(${vc},.15);color:rgb(${vc});border:1px solid rgba(${vc},.4)`;
  saveBest(p, a);
  sfx.over();
  show(overEl, true);
}

/* ------------------------------------------------------------------ *
 * best score
 * ------------------------------------------------------------------ */
const KEY = 'vocabstrike.v1';
function loadBest() {
  try { return JSON.parse(localStorage.getItem(KEY)) || {}; } catch (e) { return {}; }
}
function saveBest(p, a) {
  const b = loadBest();
  const n = {
    score: Math.max(b.score || 0, S.score),
    wave:  Math.max(b.wave || 0, S.wave),
    wpm:   Math.max(b.wpm || 0, p),
    acc:   Math.max(b.acc || 0, a),
    runs:  (b.runs || 0) + 1,
  };
  try { localStorage.setItem(KEY, JSON.stringify(n)); } catch (e) {}
  paintBest();
  $('oBest').innerHTML = `Personal best &middot; <b>${n.score.toLocaleString()}</b> pts &middot; wave <b>${n.wave}</b> &middot; <b>${n.wpm}</b> WPM &middot; <b>${n.acc}%</b>`;
}
function paintBest() {
  const b = loadBest();
  $('best').innerHTML = b.score
    ? `Personal best &middot; <b>${b.score.toLocaleString()}</b> pts &middot; wave <b>${b.wave}</b> &middot; <b>${b.wpm}</b> WPM &middot; <b>${b.acc}%</b> accuracy`
    : `No runs yet.`;
}

/* ------------------------------------------------------------------ *
 * input
 * ------------------------------------------------------------------ */
function pause() {
  if (S.mode !== 'defend' && S.mode !== 'decode') return;
  S.pausedFrom = S.mode; S.mode = 'pause';
  show(pauseEl, true);
}
function resume() {
  if (S.mode !== 'pause') return;
  S.mode = S.pausedFrom; show(pauseEl, false);
}
function toMenu() {
  S.mode = 'menu'; S.scene = null;
  show(menuEl, true); show(overEl, false); show(pauseEl, false); show(ctlEl, false);
  paintBest();
}
function toggleMute() {
  S.muted = !S.muted;
  $('btnMute').innerHTML = S.muted ? '&#128263;' : '&#128266;';
}

/* Which keys this mode consumes. Everything else falls through to the browser. */
function consumes(k) {
  switch (S.mode) {
    case 'menu':   return k === 'Enter' || k === ' ' || k === 'm' || k === 'M';
    case 'over':   return k === 'Enter' || k === ' ' || k === 'Escape';
    case 'pause':  return k === 'Escape' || k === 'Enter' || k === 'q' || k === 'Q' || k === 'm' || k === 'M';
    case 'defend': return k === 'Escape' || k === 'Backspace' || k.length === 1;
    case 'decode': return k === 'Escape' || k === 'Enter' || k === 'Backspace' || k.length === 1;
    default:       return false;
  }
}

/* Single entry point for all keystrokes — reachable from the keyboard and
   from the VS debug handle so tests can drive real gameplay. */
function pressKey(k) {
  switch (S.mode) {
    case 'menu':
      if (k === 'Enter' || k === ' ') startGame();
      else if (k === 'm' || k === 'M') toggleMute();
      return;
    case 'over':
      if (k === 'Enter' || k === ' ') startGame();
      else if (k === 'Escape') toMenu();
      return;
    case 'pause':
      if (k === 'Escape' || k === 'Enter') resume();
      else if (k === 'q' || k === 'Q') toMenu();
      else if (k === 'm' || k === 'M') toggleMute();
      return;
    case 'defend':
      if (k === 'Escape') { pause(); return; }
      if (k === 'Backspace') { clearMistake(); return; }
      if (k.length === 1) { if (S.errKey) return; handleDefendChar(k); }   // pending mistake: ignore letters
      return;
    case 'decode':
      if (k === 'Escape') { pause(); return; }
      if (k === 'Backspace') { clearMistake(); return; }
      if (k === 'Enter') { skipCard(); return; }
      if (k.length === 1) {
        if (S.cardState === 'typing') {
          if (S.errKey) return;                       // pending mistake: ignore letters
          if (eq(k, S.card.d[S.cardProg])) advanceCard(); else mistake(k);
        }
      }
      return;
  }
}

/* ------------------------------------------------------------------ *
 * custom words — the player's own deck (store lives in words.js)
 * ------------------------------------------------------------------ */
const wordsPanel = $('wordsPanel');

function openWords() {
  if (wordsPanel.hidden) {
    show(wordsPanel, true);
    renderWords();
    updateWordPreview();
  }
  const t = $('wTerm');
  t.focus(); t.select();
}

function closeWords() {
  show(wordsPanel, false);
  $('wordsForm').reset();
  const err = $('wErr');
  err.textContent = '';
  err.classList.remove('ok');
}

function updateWordPreview() {
  const W = window.VS_WORDS; if (!W) return;
  const t = W.sanitize($('wTerm').value);
  const d = W.sanitize($('wDef').value);
  const el = $('wPreview');
  el.textContent = '';
  if (!t && !d) {
    el.textContent = 'Everything you add becomes a ship you can shoot, then a definition you can decode.';
    return;
  }
  const code = (s) => { const c = document.createElement('code'); c.textContent = s; return c; };
  el.appendChild(document.createTextNode('You’ll type: '));
  if (t) el.appendChild(code(t));
  if (t && d) el.appendChild(document.createTextNode('   +   '));
  if (d) el.appendChild(code(d.length > 44 ? d.slice(0, 44) + '…' : d));
}

function renderWords() {
  const W = window.VS_WORDS; if (!W) return;
  const items = W.entries();
  const list = $('wordsList');
  $('wCount').textContent = items.length
    ? `${items.length} term${items.length === 1 ? '' : 's'} in play`
    : 'no custom terms yet';
  list.innerHTML = '';
  if (!items.length) {
    const li = document.createElement('li');
    li.className = 'wempty';
    li.textContent = 'Nothing here yet — add your first word above.';
    list.appendChild(li);
    return;
  }
  const tagFor = (id) => (id === 'mine' ? 'my deck'
    : ((DECKS.find((d) => d.id === id) || {}).label || 'my deck'));
  items.forEach((e) => {
    const li = document.createElement('li');
    const wt = document.createElement('span'); wt.className = 'wt'; wt.textContent = e.t;
    const wd = document.createElement('span'); wd.className = 'wd'; wd.textContent = e.D;
    const tg = document.createElement('span'); tg.className = 'wtag'; tg.textContent = tagFor(e.deck);
    const del = document.createElement('button');
    del.type = 'button'; del.className = 'wdel'; del.textContent = '×';
    del.title = 'Remove ' + e.t;
    del.setAttribute('aria-label', 'Remove ' + e.t);
    del.addEventListener('click', () => { W.remove(e.id); renderWords(); });
    li.append(wt, wd, tg, del);
    list.appendChild(li);
  });
}

$('addWordsBtn').addEventListener('click', openWords);
$('wordsClose').addEventListener('click', closeWords);
['wTerm', 'wDef'].forEach((id) => $(id).addEventListener('input', updateWordPreview));

$('wordsForm').addEventListener('submit', (ev) => {
  ev.preventDefault();
  const err = $('wErr');
  err.classList.remove('ok');
  const res = window.VS_WORDS.add({
    term: $('wTerm').value,
    def: $('wDef').value,
    formula: $('wFormula').value,
    deck: $('wDeck').value,
  });
  if (!res.ok) { err.textContent = res.error; return; }
  err.textContent = '';
  $('wordsForm').reset();          // onChange re-renders the list
  updateWordPreview();
  $('wTerm').focus();
});

$('wordsExport').addEventListener('click', () => {
  const blob = new Blob([window.VS_WORDS.exportJSON()], { type: 'application/json' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'vocab-strike-words.json';
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(a.href), 4000);
});

$('wordsImport').addEventListener('click', () => $('wordsFile').click());
$('wordsFile').addEventListener('change', (ev) => {
  const file = ev.target.files && ev.target.files[0];
  if (!file) return;
  const err = $('wErr');
  const fr = new FileReader();
  fr.onload = () => {
    try {
      const res = window.VS_WORDS.importJSON(String(fr.result));
      err.classList.toggle('ok', res.added > 0);
      err.textContent = res.added
        ? `Imported ${res.added} word${res.added === 1 ? '' : 's'}` +
          (res.skipped ? `, skipped ${res.skipped} duplicate${res.skipped === 1 ? '' : 's'}.` : '.')
        : `Nothing imported — ${res.skipped} duplicate${res.skipped === 1 ? '' : 's'} skipped.`;
    } catch (e) {
      err.classList.remove('ok');
      err.textContent = 'Could not read that file: ' + e.message;
    }
    ev.target.value = '';
  };
  fr.readAsText(file);
});

/* keep the pool, chips and badge in step with the store */
if (window.VS_WORDS) {
  window.VS_WORDS.onChange(() => {
    reloadVocab();
    if (S.mode === 'menu') buildMenu();
    if (!wordsPanel.hidden) renderWords();
  });
}

window.addEventListener('keydown', (ev) => {
  if (ev.ctrlKey || ev.metaKey || ev.altKey) return;
  // the word editor owns the keyboard while it is open
  if (!wordsPanel.hidden) {
    if (ev.key === 'Escape') { closeWords(); ev.preventDefault(); }
    return;
  }
  const tag = ev.target && ev.target.tagName;
  if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return;
  if (!consumes(ev.key)) return;
  ev.preventDefault();
  pressKey(ev.key);
});

$('startBtn').addEventListener('click', startGame);
$('againBtn').addEventListener('click', startGame);
$('resumeBtn').addEventListener('click', resume);
$('btnPause').addEventListener('click', () => (S.mode === 'pause' ? resume() : pause()));
$('btnMute').addEventListener('click', toggleMute);
window.addEventListener('visibilitychange', () => {
  if (document.hidden && (S.mode === 'defend' || S.mode === 'decode')) pause();
});

/* menu chips */
function buildChips(hostId, items, current, onPick) {
  const host = $(hostId);
  host.innerHTML = '';
  items.forEach((it) => {
    const b = document.createElement('button');
    b.className = 'chip';
    b.type = 'button';
    b.innerHTML = it.label + (it.sub ? `<small>${it.sub}</small>` : '');
    b.setAttribute('aria-pressed', String(it.id === current()));
    b.addEventListener('click', () => { onPick(it.id); refresh(); });
    host.appendChild(b);
  });
  function refresh() {
    [...host.children].forEach((b, i) => b.setAttribute('aria-pressed', String(items[i].id === current())));
  }
}
function deckCount(id) {
  if (id === 'all') return VOCAB.length;
  if (id === 'mine') return VOCAB.filter((e) => e.mine).length;
  return VOCAB.filter((e) => e.deck === id).length;
}
function buildMenu() {
  buildChips('decks',
    DECKS.map((d) => ({ ...d, sub: `${deckCount(d.id)} terms · ${DECK_NOTE[d.id]}` })),
    () => S.deck,
    (id) => {
      // an empty "My words" deck is an invitation to fill it
      if (id === 'mine' && !deckCount('mine')) { openWords(); return; }
      S.deck = id;
    });
  buildChips('diffs',
    DIFFS.map((d) => ({
      ...d,
      sub: `${d.spd < 1 ? 'slow' : d.spd > 1 ? 'fast' : 'steady'} ships · ${d.hp} hull`,
    })),
    () => S.diff.id,
    (id) => { S.diff = DIFFS.find((x) => x.id === id); });
  const badge = menuEl.querySelector('.badge');
  if (badge && VOCAB.length) {
    const mine = deckCount('mine');
    badge.innerHTML = `Glossary &middot; ${VOCAB.length} terms` +
      (mine ? ` &middot; ${mine} yours` : '');
  }
  paintBest();
}

/* ------------------------------------------------------------------ *
 * drawing helpers
 * ------------------------------------------------------------------ */
function drawTyped(txt, prog, x, y, font, o) {
  o = o || {};
  ctx.font = font;
  const m = font.match(/(\d+(?:\.\d+)?)px/);
  const fs = m ? parseFloat(m[1]) : 16;
  let cx = x;
  for (let i = 0; i < txt.length; i++) {
    const ch = txt[i];
    const w = ctx.measureText(ch).width;
    if (i === prog && o.caret) {
      ctx.fillStyle = o.caretBg || 'rgba(99,102,241,.55)';
      rr(cx - 1, y - fs * 0.84, w + 2, fs * 1.05, 3); ctx.fill();
    }
    ctx.fillStyle = i < prog ? (o.done || C.pos) : (i === prog ? (o.cur || C.fg) : (o.todo || C.muted));
    ctx.fillText(ch, cx, y);
    cx += w;
  }
  return cx;
}
function widthOf(txt, font) { ctx.font = font; let w = 0; for (const c of txt) w += ctx.measureText(c).width; return w; }

function wrap(text, font, maxW) {
  ctx.font = font;
  const words = text.split(' ');
  const lines = [];
  let cur = '', start = 0;
  for (const w of words) {
    const test = cur ? cur + ' ' + w : w;
    if (cur && ctx.measureText(test).width > maxW) {
      lines.push({ s: start, n: cur.length });
      start = start + cur.length + 1;
      cur = w;
    } else cur = test;
  }
  if (cur) lines.push({ s: start, n: cur.length });
  return lines;
}

function pill(x, y, text, col, font) {
  ctx.font = font || `600 10px ${SANS}`;
  const w = ctx.measureText(text).width + 16;
  rr(x, y, w, 19, 9.5);
  ctx.fillStyle = col + '22'; ctx.fill();
  ctx.strokeStyle = col + '55'; ctx.lineWidth = 1; ctx.stroke();
  ctx.fillStyle = col; ctx.textAlign = 'left'; ctx.textBaseline = 'middle';
  ctx.fillText(text, x + 8, y + 10.5);
  ctx.textBaseline = 'alphabetic';
  return w;
}

/* ------------------------------------------------------------------ *
 * scene drawing
 * ------------------------------------------------------------------ */
function drawBackground() {
  ctx.fillStyle = C.bg; ctx.fillRect(0, 0, W, H);
  const g = ctx.createRadialGradient(W * 0.22, -H * 0.1, 0, W * 0.22, -H * 0.1, H * 1.25);
  g.addColorStop(0, 'rgba(99,102,241,.20)');
  g.addColorStop(0.45, 'rgba(139,92,246,.07)');
  g.addColorStop(1, 'rgba(5,5,9,0)');
  ctx.fillStyle = g; ctx.fillRect(0, 0, W, H);
  const g2 = ctx.createRadialGradient(W * 0.88, H * 1.1, 0, W * 0.88, H * 1.1, H * 1.1);
  g2.addColorStop(0, 'rgba(34,211,238,.13)');
  g2.addColorStop(1, 'rgba(5,5,9,0)');
  ctx.fillStyle = g2; ctx.fillRect(0, 0, W, H);
}
function drawStars(dt) {
  const spd = (S.mode === 'decode' ? 14 : S.mode === 'defend' ? 42 : 16);
  ctx.save();
  for (const s of S.stars) {
    s.x -= spd * s.z * dt;
    if (s.x < -3) { s.x = W + 3; s.y = Math.random() * H; }
    ctx.globalAlpha = 0.18 + s.z * 0.55;
    ctx.fillStyle = s.z > 0.8 ? C.accent3 : '#c7d2fe';
    ctx.fillRect(s.x, s.y, s.z * 1.9, s.z * 1.9);
  }
  ctx.restore();
}

function drawHud() {
  const y = 0;
  ctx.fillStyle = 'rgba(11,11,21,.72)';
  ctx.fillRect(0, y, W, HUD_H);
  ctx.strokeStyle = C.line; ctx.lineWidth = 1;
  ctx.beginPath(); ctx.moveTo(0, HUD_H + 0.5); ctx.lineTo(W, HUD_H + 0.5); ctx.stroke();

  ctx.textBaseline = 'alphabetic'; ctx.textAlign = 'left';

  // wave badge
  let x = 24;
  ctx.font = `700 11px ${SANS}`;
  const wtxt = 'WAVE ' + String(S.wave).padStart(2, '0');
  ctx.fillStyle = C.accent3; ctx.fillText(wtxt, x, 34);
  x += ctx.measureText(wtxt).width + 18;

  // hull pips
  for (let i = 0; i < S.maxHp; i++) {
    rr(x + i * 17, 22, 12, 16, 3);
    ctx.fillStyle = i < S.hp ? C.danger : 'rgba(244,63,94,.16)';
    ctx.fill();
    if (i < S.hp) { ctx.strokeStyle = 'rgba(244,63,94,.7)'; ctx.lineWidth = 1; ctx.stroke(); }
  }
  x += S.maxHp * 17 + 6;
  ctx.font = `500 10px ${SANS}`; ctx.fillStyle = C.faint;
  ctx.fillText('HULL', x, 34);
  x += 42;

  // phase
  const phase = S.scene === 'decode' ? 'PHASE 2 · DECODE' : 'PHASE 1 · DEFEND';
  ctx.font = `600 10px ${SANS}`;
  ctx.fillStyle = S.scene === 'decode' ? C.cyan : C.accent3;
  ctx.fillText(phase, x, 34);

  // score (center)
  ctx.textAlign = 'center';
  ctx.font = `600 9.5px ${SANS}`; ctx.fillStyle = C.faint;
  ctx.fillText('SCORE', W / 2, 20);
  ctx.font = `700 24px ${MONO}`; ctx.fillStyle = C.fg;
  ctx.fillText(S.score.toLocaleString(), W / 2, 44);

  // combo
  if (S.combo > 4) {
    ctx.textAlign = 'left';
    const cm = '×' + mult();
    ctx.font = `700 15px ${MONO}`;
    const w2 = ctx.measureText(cm).width + 18;
    rr(W / 2 + 96, 20, w2, 24, 6);
    ctx.fillStyle = mult() >= 4 ? 'rgba(245,158,11,.2)' : 'rgba(139,92,246,.2)'; ctx.fill();
    ctx.strokeStyle = mult() >= 4 ? C.warn : C.accent2; ctx.lineWidth = 1; ctx.stroke();
    ctx.fillStyle = mult() >= 4 ? C.warn : '#c4b5fd';
    ctx.fillText(cm, W / 2 + 105, 37);
  }

  // right cluster: wpm / acc
  const rx = W - 200;
  ctx.textAlign = 'right';
  ctx.font = `600 9.5px ${SANS}`; ctx.fillStyle = C.faint;
  ctx.fillText('WPM', rx - 62, 20); ctx.fillText('ACC', rx, 20);
  ctx.font = `700 19px ${MONO}`;
  ctx.fillStyle = C.cyan;  ctx.fillText(Math.round(wpm()), rx - 62, 42);
  ctx.fillStyle = acc() >= 90 ? C.pos : acc() >= 75 ? C.warn : C.danger;
  ctx.fillText(Math.round(acc()) + '%', rx, 42);
  ctx.textAlign = 'left';
}

function drawPromptBar() {
  const y0 = H - PROMPT_H;
  ctx.fillStyle = 'rgba(11,11,21,.86)';
  ctx.fillRect(0, y0, W, PROMPT_H);
  ctx.strokeStyle = C.lineStrong; ctx.lineWidth = 1;
  ctx.beginPath(); ctx.moveTo(0, y0 + 0.5); ctx.lineTo(W, y0 + 0.5); ctx.stroke();

  const f = S.focus;
  let sugg = null;
  for (const e of S.enemies) if (!sugg || e.x < sugg.x) sugg = e;

  let label, txt, prog, accent;
  if (f) { label = 'ENGAGED'; txt = f.txt; prog = f.prog; accent = C.accent3; }
  else if (sugg) {
    label = 'TARGET ' + (S.enemies.indexOf(sugg) + 1);
    txt = sugg.txt; prog = 0; accent = C.warn;
  } else {
    label = 'INBOUND'; txt = 'stand by'; prog = 0; accent = C.faint;
  }

  ctx.textAlign = 'left'; ctx.textBaseline = 'alphabetic';
  ctx.font = `600 9.5px ${SANS}`;
  ctx.fillStyle = accent;
  ctx.fillText(label, 28, y0 + 26);
  ctx.fillStyle = S.errKey ? C.danger : C.faint;
  ctx.fillText(S.errKey ? 'PRESS BACKSPACE TO CLEAR THE MISTAKE'
                        : (f || sugg ? 'TYPE THE TERM' : 'SCANNING'),
               28 + ctx.measureText(label).width + 14, y0 + 26);

  // big typing line
  const avail = W - 28 - 190;
  let fs = 30;
  let font = `600 ${fs}px ${MONO}`;
  let tw = widthOf(txt, font);
  if (tw > avail) { fs = Math.max(14, fs * avail / tw); font = `600 ${fs}px ${MONO}`; tw = widthOf(txt, font); }
  drawTyped(txt, prog, 28, y0 + 78, font, {
    caret: true, done: C.pos, cur: '#fff', todo: f ? C.muted : 'rgba(154,160,186,.5)',
    caretBg: S.errKey ? 'rgba(244,63,94,.75)' : 'rgba(99,102,241,.6)',
  });

  // next key — or the mistake that must be cleared with Backspace
  const nk = (f || sugg) ? txt[prog] : undefined;
  const bx = W - 28 - 150, by = y0 + 40;
  if (S.errKey) {
    ctx.font = `600 9.5px ${SANS}`; ctx.fillStyle = C.danger;
    ctx.fillText('PRESSED — HIT BACKSPACE', bx, by - 8);
    const lbl = keyLabel(S.errKey);
    ctx.font = `700 ${lbl.length > 3 ? 15 : 26}px ${MONO}`;
    const kw = Math.max(78, ctx.measureText(lbl).width + 26);
    rr(bx, by, kw, 48, 9);
    ctx.fillStyle = 'rgba(244,63,94,.16)'; ctx.fill();
    ctx.strokeStyle = C.danger; ctx.lineWidth = 1.5; ctx.stroke();
    ctx.fillStyle = '#fff'; ctx.textBaseline = 'middle';
    ctx.fillText(lbl, bx + 13, by + 25);
    ctx.textBaseline = 'alphabetic';
  } else if (nk !== undefined) {
    ctx.font = `600 9.5px ${SANS}`; ctx.fillStyle = C.faint;
    ctx.fillText('NEXT KEY', bx, by - 8);
    const lbl = keyLabel(nk);
    ctx.font = `700 ${lbl.length > 3 ? 15 : 26}px ${MONO}`;
    const kw = Math.max(78, ctx.measureText(lbl).width + 26);
    rr(bx, by, kw, 48, 9);
    ctx.fillStyle = 'rgba(99,102,241,.16)'; ctx.fill();
    ctx.strokeStyle = C.accent; ctx.lineWidth = 1.5; ctx.stroke();
    ctx.fillStyle = '#fff'; ctx.textBaseline = 'middle';
    ctx.fillText(lbl, bx + 13, by + 25);
    ctx.textBaseline = 'alphabetic';
  }

  // combo meter
  const cb = Math.min(1, (S.combo % 15) / 15);
  ctx.fillStyle = 'rgba(255,255,255,.06)';
  ctx.fillRect(28, y0 + PROMPT_H - 14, W - 56, 4);
  ctx.fillStyle = mult() >= 4 ? C.warn : C.accent2;
  ctx.fillRect(28, y0 + PROMPT_H - 14, (W - 56) * cb, 4);
}

function drawShip(e) {
  const x = e.x - e.w / 2, y = e.y - e.h / 2;
  const urgent = e.x - e.w / 2 < 240;
  const col = urgent ? C.danger : (S.focus === e ? C.accent : C.accent3);

  // engine trail
  const trail = ctx.createLinearGradient(x + e.w, 0, x + e.w + 70, 0);
  trail.addColorStop(0, (urgent ? 'rgba(244,63,94,' : 'rgba(99,102,241,') + '0.42)');
  trail.addColorStop(1, 'rgba(99,102,241,0)');
  ctx.fillStyle = trail;
  ctx.fillRect(x + e.w, e.y - 4 + Math.sin(e.wob) * 2, 70, 8);

  // hull
  rr(x, y, e.w, e.h, 11);
  ctx.fillStyle = S.focus === e ? 'rgba(31,31,49,.96)' : 'rgba(22,22,38,.9)';
  ctx.fill();
  ctx.lineWidth = S.focus === e ? 2 : 1;
  ctx.strokeStyle = col;
  if (S.focus === e) { ctx.shadowColor = C.accent; ctx.shadowBlur = 16; }
  ctx.stroke();
  ctx.shadowBlur = 0;

  // domain stripe
  const stripe = { controls: C.warn, ml: C.accent2, mech: C.cyan }[e.e.deck] || C.faint;
  rr(x + 8, e.y - 8, 3, 16, 1.5);
  ctx.fillStyle = stripe; ctx.fill();

  // term
  const font = `600 ${e.fs}px ${MONO}`;
  ctx.font = font;
  const tx = x + 24;
  drawTyped(e.txt, e.prog, tx, e.y + e.fs * 0.36, font, {
    caret: S.focus === e, done: C.pos, cur: '#fff', todo: C.muted,
    caretBg: 'rgba(99,102,241,.7)',
  });

  // progress underline
  const p = e.prog / e.txt.length;
  if (p > 0) {
    ctx.fillStyle = C.pos;
    ctx.fillRect(tx, y + e.h - 5, (e.w - 34) * p, 2.5);
  }
}

function drawPlayer() {
  const y = midY();
  ctx.save();
  ctx.translate(PX, y);
  // shield arc
  ctx.beginPath();
  ctx.arc(6, 0, 30, -Math.PI * 0.42, Math.PI * 0.42);
  ctx.strokeStyle = 'rgba(34,211,238,.35)'; ctx.lineWidth = 2; ctx.stroke();
  // body
  ctx.beginPath();
  ctx.moveTo(20, 0); ctx.lineTo(-8, -16); ctx.lineTo(-20, -9);
  ctx.lineTo(-20, 9); ctx.lineTo(-8, 16); ctx.closePath();
  ctx.fillStyle = C.ink700; ctx.fill();
  ctx.strokeStyle = C.cyan; ctx.lineWidth = 1.5; ctx.stroke();
  ctx.beginPath(); ctx.arc(4, 0, 5, 0, 6.283);
  ctx.fillStyle = C.cyan; ctx.fill();
  // thruster
  const th = 10 + Math.sin(performance.now() / 90) * 5;
  ctx.beginPath();
  ctx.moveTo(-21, -6); ctx.lineTo(-21 - th, 0); ctx.lineTo(-21, 6); ctx.closePath();
  ctx.fillStyle = 'rgba(99,102,241,.75)'; ctx.fill();
  ctx.restore();
}

function drawDefend() {
  drawPlayer();
  for (const e of S.enemies) drawShip(e);
  drawPromptBar();
}

/* ---- decode ---- */
/* panel geometry, shared by the renderer and the score float */
function decodeBox() {
  const panelW = Math.min(880, W - 56);
  const c = S.card;
  const lines = wrap(c ? c.d : '', `500 21px ${MONO}`, panelW - 80);
  const showing = !c || S.cardState !== 'typing';
  const lastY = 170 + (lines.length - 1) * 32;
  let panelH = showing ? lastY + 86 : lastY + 40;
  panelH = clamp(panelH, 200, Math.max(300, H - HUD_H - 80));
  return {
    panelW, panelH,
    px: (W - panelW) / 2,
    py: HUD_H + Math.max(16, (H - HUD_H - panelH) / 2 - 6),
  };
}

function drawDecode() {
  const c = S.card; if (!c) return;

  const { px, py, panelW, panelH } = decodeBox();
  const cx = px + 40, cw = panelW - 80;
  const ff = `500 21px ${MONO}`;
  const lineH = 32;
  const lines = wrap(c.d, ff, cw);
  const showing = S.cardState !== 'typing';
  const reserved = showing ? 0 : 150;   // room for the NEXT KEY box

  rr(px, py, panelW, panelH, 18);
  ctx.fillStyle = 'rgba(11,11,21,.92)'; ctx.fill();
  ctx.strokeStyle = C.lineStrong; ctx.lineWidth = 1; ctx.stroke();

  const left = Math.max(0, S.cardT / S.cardLimit);

  // timer bar along the panel's top edge
  ctx.save();
  rr(px + 1, py + 1, panelW - 2, 7, 3); ctx.clip();
  ctx.fillStyle = 'rgba(255,255,255,.07)'; ctx.fillRect(px, py, panelW, 9);
  ctx.fillStyle = left > 0.5 ? C.pos : left > 0.25 ? C.warn : C.danger;
  ctx.fillRect(px, py, panelW * left, 9);
  ctx.restore();

  ctx.textAlign = 'left'; ctx.textBaseline = 'alphabetic';
  const y = py + 50;

  // header
  const stripe = { controls: C.warn, ml: C.accent2, mech: C.cyan }[c.deck] || C.faint;
  let hx = cx;
  hx += pill(hx, y - 14, c.dom.toUpperCase(), stripe) + 10;
  hx += pill(hx, y - 14, 'SIGNAL ' + (S.qi + 1) + '/' + S.queue.length, C.accent3) + 10;
  pill(hx, y - 14, '×' + mult(), C.warn);

  ctx.textAlign = 'right';
  ctx.font = `700 20px ${MONO}`;
  ctx.fillStyle = left > 0.25 ? C.fg : C.danger;
  ctx.fillText(S.cardT.toFixed(1) + 's', px + panelW - 40, y + 6);
  ctx.textAlign = 'left';

  // term, plus the source formula beside it when there's room
  const ty = py + 106;
  const avail = px + panelW - 40 - reserved - cx;
  let tf = `700 34px ${MONO}`;
  let twid = widthOf(c.T, tf);
  if (twid > avail) { tf = `700 ${Math.max(17, 34 * avail / twid)}px ${MONO}`; twid = widthOf(c.T, tf); }
  ctx.font = tf; ctx.fillStyle = C.accent3;
  ctx.fillText(c.T, cx, ty);
  if (c.f) {
    ctx.font = `500 13px ${MONO}`;
    const fw = ctx.measureText(c.f).width;
    if (twid + 20 + fw <= avail) {
      ctx.fillStyle = C.faint;
      ctx.fillText(c.f, cx + twid + 20, ty);
    }
  }

  // instruction
  ctx.font = `600 9.5px ${SANS}`; ctx.fillStyle = S.errKey ? C.danger : C.faint;
  ctx.fillText(S.errKey ? 'MISTAKE — PRESS BACKSPACE TO CLEAR' : 'TYPE THE DEFINITION', cx, py + 136);

  // definition — wrapped, coloured per keystroke
  const dy = py + 170;
  for (let li = 0; li < lines.length; li++) {
    const L = lines[li];
    const ly = dy + li * lineH;
    if (showing && ly > py + panelH - 46) break;
    drawTyped(c.d.substr(L.s, L.n), Math.max(0, S.cardProg - L.s), cx, ly, ff, {
      caret: S.cardState === 'typing' && S.cardProg >= L.s && S.cardProg <= L.s + L.n,
      done: C.pos, cur: '#fff', todo: C.muted,
      caretBg: S.errKey ? 'rgba(244,63,94,.75)' : 'rgba(34,211,238,.55)',
    });
  }

  // result banner
  if (S.cardState !== 'typing') {
    const ok = S.cardState === 'done';
    const by = py + panelH - 44;
    rr(cx, by - 4, cw, 40, 9);
    ctx.fillStyle = ok ? 'rgba(16,185,129,.14)' : 'rgba(245,158,11,.14)'; ctx.fill();
    ctx.strokeStyle = ok ? C.pos : C.warn; ctx.lineWidth = 1; ctx.stroke();
    ctx.font = `700 10px ${SANS}`;
    ctx.fillStyle = ok ? C.pos : C.warn;
    ctx.fillText(ok ? '✓ MASTERED' : (S.cardState === 'skip' ? 'SKIPPED' : '✗ TIMER EXPIRED'), cx + 14, by + 21);

    // canonical, original-source text
    ctx.font = `500 13px ${SANS}`;
    ctx.fillStyle = C.fg;
    const ref = (c.f ? c.f + '  —  ' : '') + c.D;
    let shown = ref;
    while (ctx.measureText(shown).width > cw - 150 && shown.length > 10) shown = shown.slice(0, -2) + '…';
    ctx.textAlign = 'right';
    ctx.fillText(shown, px + panelW - 40, by + 21);
    ctx.textAlign = 'left';
  }

  // next key — or the mistake that must be cleared with Backspace
  const pending = S.cardState === 'typing' && S.errKey;
  const nk = S.cardState === 'typing' && !S.errKey ? S.card.d[S.cardProg] : null;
  if (pending) {
    const bx = px + panelW - 40 - 96, byy = py + 96;
    ctx.font = `600 9px ${SANS}`; ctx.fillStyle = C.danger; ctx.textAlign = 'right';
    ctx.fillText('PRESSED — HIT BACKSPACE', bx + 96, byy - 7);
    const lbl = keyLabel(S.errKey);
    ctx.font = `700 ${lbl.length > 3 ? 13 : 22}px ${MONO}`;
    const kw = Math.max(74, ctx.measureText(lbl).width + 22);
    rr(bx + 96 - kw, byy, kw, 42, 8);
    ctx.fillStyle = 'rgba(244,63,94,.15)'; ctx.fill();
    ctx.strokeStyle = C.danger; ctx.lineWidth = 1.5; ctx.stroke();
    ctx.fillStyle = '#fff'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
    ctx.fillText(lbl, bx + 96 - kw / 2, byy + 22);
    ctx.textBaseline = 'alphabetic'; ctx.textAlign = 'left';
  } else if (nk !== undefined && nk != null) {
    const bx = px + panelW - 40 - 96, byy = py + 96;
    ctx.font = `600 9px ${SANS}`; ctx.fillStyle = C.faint; ctx.textAlign = 'right';
    ctx.fillText('NEXT KEY', bx + 96, byy - 7);
    const lbl = keyLabel(nk);
    ctx.font = `700 ${lbl.length > 3 ? 13 : 22}px ${MONO}`;
    const kw = Math.max(74, ctx.measureText(lbl).width + 22);
    rr(bx + 96 - kw, byy, kw, 42, 8);
    ctx.fillStyle = 'rgba(34,211,238,.15)'; ctx.fill();
    ctx.strokeStyle = C.cyan; ctx.lineWidth = 1.5; ctx.stroke();
    ctx.fillStyle = '#fff'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
    ctx.fillText(lbl, bx + 96 - kw / 2, byy + 22);
    ctx.textBaseline = 'alphabetic'; ctx.textAlign = 'left';
  }

  // footer hint
  ctx.font = `500 11px ${SANS}`; ctx.fillStyle = C.faint; ctx.textAlign = 'center';
  ctx.fillText('Esc pause  ·  Enter skip this definition  ·  a wrong key locks the word until you hit Backspace', W / 2, py + panelH + 24);
  ctx.textAlign = 'left';
}

function drawFx(dt) {
  // beams
  for (let i = S.beams.length - 1; i >= 0; i--) {
    const b = S.beams[i];
    b.t += dt;
    if (b.t >= b.dur) { S.beams.splice(i, 1); continue; }
    const a = 1 - b.t / b.dur;
    ctx.strokeStyle = b.red ? `rgba(244,63,94,${a})` : `rgba(34,211,238,${a})`;
    ctx.lineWidth = 2 + a * 3;
    ctx.beginPath(); ctx.moveTo(b.x1, b.y1); ctx.lineTo(b.x2, b.y2); ctx.stroke();
  }
  // particles
  for (let i = S.particles.length - 1; i >= 0; i--) {
    const p = S.particles[i];
    p.t += dt;
    if (p.t >= p.dur) { S.particles.splice(i, 1); continue; }
    p.x += p.vx * dt; p.y += p.vy * dt;
    const damp = Math.pow(0.046, dt);   // ≈ 0.95/frame at 60fps, frame-rate independent
    p.vx *= damp; p.vy *= damp;
    ctx.globalAlpha = 1 - p.t / p.dur;
    ctx.fillStyle = p.col;
    ctx.fillRect(p.x, p.y, p.size, p.size);
  }
  ctx.globalAlpha = 1;
  // floats
  ctx.textAlign = 'center';
  for (let i = S.floats.length - 1; i >= 0; i--) {
    const f = S.floats[i];
    f.t += dt;
    if (f.t >= f.dur) { S.floats.splice(i, 1); continue; }
    const a = 1 - f.t / f.dur;
    ctx.globalAlpha = a;
    ctx.font = `700 17px ${MONO}`;
    ctx.fillStyle = f.col;
    ctx.fillText(f.text, f.x, f.y - f.t * 42);
  }
  ctx.globalAlpha = 1;
  ctx.textAlign = 'left';
}

function drawToast(dt) {
  if (!S.toast) return;
  const t = S.toast;
  t.t += dt;
  if (t.t >= t.dur) { S.toast = null; return; }
  const a = Math.min(1, t.t * 4) * Math.min(1, (t.dur - t.t) * 2.2);
  ctx.globalAlpha = a;
  ctx.textAlign = 'center';
  // during DECODE, sit clear above the signal panel instead of mid-screen
  let y = H * 0.42;
  if (S.scene === 'decode' && S.card) y = Math.max(HUD_H + 44, decodeBox().py - 46);
  ctx.font = `800 46px ${SANS}`;
  ctx.fillStyle = t.col;
  ctx.fillText(t.text, W / 2, y);
  if (t.sub) {
    ctx.font = `500 15px ${SANS}`;
    ctx.fillStyle = C.muted;
    ctx.fillText(t.sub, W / 2, y + 30);
  }
  ctx.globalAlpha = 1;
  ctx.textAlign = 'left';
}

/* ------------------------------------------------------------------ *
 * loop
 * ------------------------------------------------------------------ */
function update(dt) {
  const live = S.mode === 'defend' || S.mode === 'decode';
  if (live) S.playMs += dt * 1000;

  if (S.mode === 'defend') updateDefend(dt);
  else if (S.mode === 'decode') updateDecode(dt);

  if (S.mode !== 'pause') {
    S.flash = Math.max(0, S.flash - dt * 2.4);
    S.shake = Math.max(0, S.shake - dt * 34);
  }
}

function render(dt) {
  ctx.save();
  if (S.shake > 0.4) ctx.translate(rnd(-S.shake, S.shake) * 0.5, rnd(-S.shake, S.shake) * 0.5);

  drawBackground();
  drawStars(dt);

  const scene = S.mode === 'pause' ? S.pausedFrom : S.scene;
  if (scene === 'defend') { drawHud(); drawDefend(); }
  else if (scene === 'decode') { drawHud(); drawDecode(); }

  const fx = S.mode === 'pause' ? 0 : dt;
  drawFx(fx);
  if (S.mode !== 'menu' && S.mode !== 'over' && S.mode !== 'pause') drawToast(fx);

  if (S.flash > 0) {
    ctx.globalAlpha = Math.min(0.4, S.flash);
    ctx.fillStyle = S.flashCol;
    ctx.fillRect(0, 0, W, H);
    ctx.globalAlpha = 1;
  }
  ctx.restore();
}

let last = performance.now();
function frame(now) {
  let dt = (now - last) / 1000; last = now;
  if (dt > 0.06) dt = 0.06;
  if (S.mode !== 'pause') update(dt);
  render(dt);
  requestAnimationFrame(frame);
}

/* ------------------------------------------------------------------ *
 * boot
 * ------------------------------------------------------------------ */
if (!VOCAB.length) {
  document.body.innerHTML = '<div style="padding:40px;font:16px system-ui;color:#f43f5e">' +
    'data.js is missing or empty &mdash; run <code>build_data.py</code> first.</div>';
  return;
}
S.salvage = [];
resize();
initStars();
buildMenu();
requestAnimationFrame(frame);

/* Dev handle: inspect state from devtools, or drive the game from a test.
   `VS.S` is the live state object; `VS.pressKey('a')` is a keystroke. */
window.VS = { S, pressKey, start: startGame, openWords, closeWords };

})();
